language: node_js
node_js:
  - "lts/*"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
   - npm run lint ngx-drag-scroll
   - npm run test ngx-drag-scroll
   - npm run build ngx-drag-scroll
