language: node_js
node_js:
  - "lts/*"
dist: xenial

services:
  - xvfb

addons:
  chrome: stable

script:
   - npm run lint ngx-drag-scroll
   - npm run test ngx-drag-scroll
   - npm run build ngx-drag-scroll
